version: '{branch}-{build}'
build: off
image: Visual Studio 2019
environment:
  matrix:
    - TOXENV: check
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    - TOXENV: py39-opencv44-numpy121
      TOXPYTHON: C:\Python39\python.exe
      PYTHON_HOME: C:\Python39
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '32'
    - TOXENV: py39-opencv44-numpy121
      TOXPYTHON: C:\Python39-x64\python.exe
      PYTHON_HOME: C:\Python39-x64
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '64'
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - '%PYTHON_HOME%\python -mpip install --progress-bar=off tox -rci/requirements.txt'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - %PYTHON_HOME%\Scripts\tox
on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
